server:
  port: 9000

spring:
  profiles:
    active: native
  application:
    name: test-cloud-config   # 应用名称
  cloud:
    inetutils:
      use-only-site-local-interfaces: true    # 注册时使用本站地址
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/    # 注册中心地址
  instance:
    prefer-ip-address: true # 注册IP 而不是主机名

# INFO
info:
  spring:
    profiles:
      active: ${spring.profiles.active}
  app:
    name: ${spring.application.name}
    eureka: ${eureka.client.service-url.defaultZone}


---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Zhong_CW/test-cloud-config-repo/
#          username: Zhong_CW
#          password: zswdgitmm
#          search-paths:
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/repo/
#---
#spring:
#  profiles: svn